### ISSUE TITLE
Fortune of lapis doesn't work and cut gem  unattainable

### ISSUE THREAD

**Issue by VaguesTicon** [ferriarnus/TinkersJewelry#13]
Hi Ferri,I wonder if the fortune enchantment effect of lapis works?
I got a fortune effect from odds and ends（of course in tinker's jewelry) that's equal to fortune V but it works not satisfactorily,hardly takes effect.
And the emerald  cut gem and diamond cut gem aren't accessible ,recipe exists but you can't make them.

**Comment by DankestO** [comment]
I was just coming to report this and you got there first. xD

- Answering your question, that upgrade actually stacked with the existing fortune on the pickaxe. You should have earned a ton more items, but since the latest Tconstruct updates, several Tinker's Jewelry abilities stopped working.

I thought it was my problem, but no, it seems to be some kind of bug. Hopefully, these issues will be fixed soon. :(

**Comment by ferriarnus** [comment]
So this doesn't happen for me? There must be another mod messing with it. What mods are you using?

**Comment by ferriarnus** [comment]
Tinker's Calibration is causing this, I'll look for a fix

**Comment by ferriarnus** [comment]
So the issue with Tinker's Calibration should be fixed for lapis and diamond. Fortune however is working fine for me, so unsure what mod causes that issue.

**Comment by kygil5517-lab** [comment]
> So the issue with Tinker's Calibration should be fixed for lapis and diamond. Fortune however is working fine for me, so unsure what mod causes that issue.

This issue is still occurring for me and most Ring upgrades aren’t working, the rings for me break full durability once i log off and back on

**Comment by DankestO** [comment]
I have a question about this...
Does the pickaxe need to have Fortune applied for the ring's "Fortune" effect to work?
Or does simply wearing the ring automatically grant Fortune on all tools you use?

And, for those of you experiencing this issue, could you share your mod list? I'd like to compare and see if any Tinkers addons, or other mods, are causing this, and eliminate potential causes instead of having to remove all 200 mods I have one by one. xD

Here are the mods I use:

<img width="1862" height="1004" alt="Image" src="https://github.com/user-attachments/assets/5aa7fb73-0ef8-47ca-8e48-a929cbf12070" />

**Comment by Jthirteen13** [comment]
> I have a question about this... Does the pickaxe need to have Fortune applied for the ring's "Fortune" effect to work? Or does simply wearing the ring automatically grant Fortune on all tools you use?
> 
> And, for those of you experiencing this issue, could you share your mod list? I'd like to compare and see if any Tinkers addons, or other mods, are causing this, and eliminate potential causes instead of having to remove all 200 mods I have one by one. xD
> 
> Here are the mods I use:
> <img alt="Image" width="1862" height="1004" src="https://private-user-images.githubusercontent.com/126206944/511729176-5aa7fb73-0ef8-47ca-8e48-a929cbf12070.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjMwNzAzMTAsIm5iZiI6MTc2MzA3MDAxMCwicGF0aCI6Ii8xMjYyMDY5NDQvNTExNzI5MTc2LTVhYTdmYjczLTBlZjgtNDdjYS04ZTQ4LWE5MjljYmYxMjA3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTExM1QyMTQwMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNWE2MzEzNDMyMjBmOGM5MDUzNWQzMWI3YTQ3ZTg4YzkzNWY3MzY4NGM1ZWU3MDM4OWE3NmVlMWUxZGM3N2NkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Gf0IhJxFaPVkH5vMmV3FIPis_cRM6TtJOdkxn2Fm9Dw">

Mayhaps attributefix? I have that mod as well and it *seems* like the most likely culprit

**Comment by Jthirteen13** [comment]
> > I have a question about this... Does the pickaxe need to have Fortune applied for the ring's "Fortune" effect to work? Or does simply wearing the ring automatically grant Fortune on all tools you use?
> > And, for those of you experiencing this issue, could you share your mod list? I'd like to compare and see if any Tinkers addons, or other mods, are causing this, and eliminate potential causes instead of having to remove all 200 mods I have one by one. xD
> > Here are the mods I use:
> > <img alt="Image" width="1862" height="1004" src="https://private-user-images.githubusercontent.com/126206944/511729176-5aa7fb73-0ef8-47ca-8e48-a929cbf12070.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjMwNzAzMTAsIm5iZiI6MTc2MzA3MDAxMCwicGF0aCI6Ii8xMjYyMDY5NDQvNTExNzI5MTc2LTVhYTdmYjczLTBlZjgtNDdjYS04ZTQ4LWE5MjljYmYxMjA3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTExM1QyMTQwMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNWE2MzEzNDMyMjBmOGM5MDUzNWQzMWI3YTQ3ZTg4YzkzNWY3MzY4NGM1ZWU3MDM4OWE3NmVlMWUxZGM3N2NkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Gf0IhJxFaPVkH5vMmV3FIPis_cRM6TtJOdkxn2Fm9Dw">
> 
> Mayhaps attributefix? I have that mod as well and it _seems_ like the most likely culprit

No, or at least, nothing changed when disabled. I can also rule out modernfix, ferritecore, and I  couldn't find anything that'd point to it being quark but do take that with a grain of salt as I did not try disabling it and testing, so...
otherwise, the list *is* slightly shorter
